### ISSUE TITLE
http://cstadler.aksw.org/repos/apt is no accessible

### ISSUE THREAD

**Issue by bdecarne** [GeoKnow/LinkedGeoData#23]
I'm unable too reach http://cstadler.aksw.org/repos/apt, as same as http://linkedgeodata.org ?

What's wrong ?

**Comment by akuckartz** [comment]
Both are accessible from here.

**Comment by Aklakan** [comment]
There was some consolidation of our infrastructure such as changing IPs which most likely caused temporal downtimes. I'm closing the issue as both links are working and I am not aware of immanent further changes.
