### ISSUE TITLE
Make Interlink files part of the debian package(s)

### ISSUE THREAD

**Issue by Aklakan** [GeoKnow/LinkedGeoData#28]

**Comment by akuckartz** [comment]
?

**Comment by Aklakan** [comment]
The interlinks are now [decade old](https://github.com/LATC/24-7-platform/tree/master/link-specifications) and most likely of no more use. Removed them form the debian package. Also, nowadays there are links from osm to wikidata and vice versa which is presumably more stable than this unreliable external interlinking.
